spring.application.name=demo

# 接続先のURL（rental_db に繋ぐ設定）
spring.datasource.url=jdbc:mysql://localhost:3306/rental_db

# データベースのユーザー名（ご自身の環境に合わせてください。初期は root が多いです）
spring.datasource.username=root

# データベースのパスワード（設定している場合）
spring.datasource.password=shun2002

# データベースのドライバー
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

